{% set version = "1.005" %}

package:
  name: perl-business-issn
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-{{ version }}.tar.gz
  sha256: 3b09b0267f0a6660fb92b6f50c4c7796ef6a263b62ad3bbeaa07189a0c7c39b3

build:
  script: |
    perl Makefile.PL INSTALLDIRS=vendor
    make
    make test
    make install
  noarch: generic
  number: 0
  run_exports:
    weak:
      - perl-business-issn ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Business::ISSN

about:
  home: https://metacpan.org/pod/Business::ISSN
  license: Artistic-2.0
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: Perl package to work with International Standard Serial Numbers

extra:
  recipe-maintainers:
    - njzjz
